version: '3.8'
services:
  ptag-local:
    image: "postgres:latest"
    container_name: ptag-local
    ports:
      - "5432:5432"
    volumes:
      - "/home/qayyuum/postgres/:/var/lib/postgresql/data"
  redis-local:
    image: "redis:alpine"
    container_name: redis-local
    ports:
      - "6379:6379"